### PR TITLE
review of chairs document

### PR DESCRIPTION
**Pull request by SimonHallen**
review of chairs document. Finding duplicates etc

### CODE REVIEW

**Comment by MansMeg** [comment]
There seem to be a crazy amount of edits. Im not sure why. My guess is that the file has some wrong formating somehow. We need to fix this. @BobBorges do you see what whent wrong?

**Comment by MansMeg** [comment]
Yes and the chair test also fails.

**Comment by BobBorges** [comment]
Simon added a column -- I didn't anticipate that / warn about it. I will fetch this file and somehow try to see only the meaningful changes + removing the extra column.

**Comment by ninpnin** [comment]
Maybe my git-comma-diff would come in handy?
```fish
git diff --word-diff-regex=[^[:space:],]+ $argv
```

**Comment by BobBorges** [comment]
@fredrik1984 
[50-random-edited-rows.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14167621/50-random-edited-rows.csv)
please have a look

**Comment by MansMeg** [comment]
? The test still fails? We want to fix that first?

**Comment by BobBorges** [comment]
The test fails because the delimiter changed so it doesn't find the columns. I want to make sure that we can see what Simon actually changed and that those edits are reasonable (hence the csv w/ tagged Fredrik) before I start messing with the file. Right now the edits look reasonable, but I'd like a second opinion, then it's just a few minutes to fix the formatting.

**Comment by MansMeg** [comment]
It is always better to fix the tests first. Otherwise, we might find new bugs after @fredrik1984 has done his checks.

**Comment by MansMeg** [comment]
Why not just remove the column? You could do a separate PR to see the diffs?

**Comment by BobBorges** [comment]
@fredrik1984 -- chairs test, as it was before simon's work passes.

**Comment by MansMeg** [comment]
Yay!

**Comment by BobBorges** [comment]
Don't merge yet...

**Comment by BobBorges** [comment]
The tests that were already running on the chairs data are now passing, but there are three skipped tests that still fail. I think we can merge the data as it is and potentially continue fixing inaccuracies. What do you all say? @MansMeg  @ninpnin 

@SimonHallen I'm attaching some files from unit tests here. Do you think you will have time to look at some of these?

- ChairHog and LoveSeats are the same as before, but much shorter than last time you got them. n.b. my ChairHog test automatically flagged people sitting in different chambers, but if this is allowed I can modify
- EmptySeats: empty chairs by year: only a hand full are in the time frame you guys are working with

Also @LaurineMir went through some of the places where the matriklar didn't line up with the Swerik metadata and I'm also attaching a list of issues that might be related to OCR, like the year is wrong and in some cases the MP was long dead by the time of the seat datum. Maybe you could have a look at some of those, as it's relevant for the result of your project.

[20240206-1551_ChairHogs.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14182017/20240206-1551_ChairHogs.csv)
[20240206-1551_EmptySeats.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14182018/20240206-1551_EmptySeats.csv)
[20240206-1551_LoveSeats.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14182019/20240206-1551_LoveSeats.csv)
[probable_ocr-err_in_matriklarna.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14182027/probable_ocr-err_in_matriklarna.csv)

**Comment by SimonHallen** [comment]
I'll take a look at it!

**Pull request merged**
