### PR TITLE
v0.4.1

### PR DESCRIPTION
**Pull request by ninpnin**
- Fix bug that affected names.csv
- Add precise dates for protocols 1990->
- Refactor and fix minor bugs

### CODE REVIEW

**Comment by rbbby** [comment]
Should probably adapt redetect.py to account for new improved dates + filter by year for when the dates are bad. Plus run redetect before merging?

**Comment by MansMeg** [comment]
Failing unit tests?

**Comment by rbbby** [comment]
LGTM

**Comment by MansMeg** [comment]
Still failing?

**Comment by rbbby** [comment]
The tests have not been updated for version 4, it looks for protocols in for example 'corpus/1955/prot-1955--ak--22.xml', but they are in 'corpus/protocols/1955/prot-1955--ak--22.xml' now.

**Comment by MansMeg** [comment]
Ok. Please update the test so that they do not fail. We should only merge data that passes the test.

**Pull request merged**
