### PR TITLE
added twitter handles and party abbreviation for largest parties

### PR DESCRIPTION
**Pull request by fellennert**
I added the Twitter handles from peterdalle/swedishtwitter plus some party abbreviations that were on Wikipedia (https://en.wikipedia.org/wiki/List_of_political_parties_in_Sweden#Minor_parties).

### CODE REVIEW

**Comment by MansMeg** [comment]
This is great Felix. I assume you added two csv columns? I cant see due to the large number of changed lines?

Maybe it is best if @ninpnin do a review of the proposed additions?

**Comment by fellennert** [comment]
Hi Maans, 
yes, exactly. One with the Twitter handle (`twittername`) and one with the party abbreviation (`party_abbrev`). Just let me know if there's anything that's needed to be done (also, I can add other abbreviations quite easily, I just need to know them).

**Comment by Stubbendorff** [comment]
Hi Felix! Send us a list of the party abbrevations you don't know and we will figure it out. /Johan

**Comment by MansMeg** [comment]
Yay! This is starting to become a real research collaboration now!

**Comment by fellennert** [comment]
Unfortunately on my very last day as a paid M4M research assistant, haha. 

Great! It's not many, but:
- Bondeförbundet
- is "Centern" the same as centerpartiet? Also, why is there "Centern [1]"?
- "Ernst Trygger"/"Hugo Erik Gustaf Hamilton"/"Johan Östberg" – those are not parties, right?
- Folkpartiet/Folkpartiet liberalerna/Folkpartiet Liberalerna (again, three different names for one party, I guess?)
- för Jönköping
- Högerpartiet
- Moderaterna
- Ny demokrati
- Vänsterpartiet kommunisterna (it's equivalent to "Vänsterpartiet", right?)

**Comment by Stubbendorff** [comment]
Bondeförbundet = Centern

Every "Centern" should be the modern Centern. On wikipedia it says that it might also be "Centern (1985 – rikstäckande valteknisk samarbete mellan Centerpartiet och KDS)", but we should label it Centern anyway. Centerpartiet is the same party, as is Bondeförbundet.

Trygger and the others are not parties. When we imported data from Wikipedia, some MP info got in the wrong column. "för Jönköping" is probably explained by that as well.

Folkpartiet etc are the same as Liberalerna today.

Högerpartiet = Moderaterna

Ny demokrat, the abbrevation is often NYD

Vänsterpartiet kommunisterna = "Vänsterpartiet", and so is "Sveriges kommunistiska parti" (Skp) from 1921 to 1967

You don't have any others? There might be a few MP:s elected for established parties, but changing to new parties once while in parliament.

**Comment by fellennert** [comment]
Thanks, fixed it. Those are the ones I could not match:
image

**Comment by ninpnin** [comment]
Could this be done to the mp branch with the new mp data instead? It's a bit of a technical issue to merge it to main.

**Comment by ninpnin** [comment]
Replaced by #69

**Pull request closed without merging**
