### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by ninpnin**
Preliminarily use the MIT License for the whole codebase and data.

### CODE REVIEW

**Comment by MansMeg** [comment]
I could look this up. We were in contact with the library of the Riksdag. So they might know exactly what LICENSE we can have.

**Comment by MansMeg** [comment]
Pelle says use this one for the data:
https://creativecommons.org/licenses/by/2.0/

For the code we can use MIT.

**Comment by ninpnin** [comment]
Everything in corpus/ would then be CCBY licenced, and everything in pyriksdagen/ and scripts/ would be MIT licenced. Maybe create LICENCE files in those folders, and a general custom LICENCE file on project root that that the licences are specified in subfolders.

**Comment by MansMeg** [comment]
Sounds good! I think we will move out the libraries later on.

**Comment by ninpnin** [comment]
Done. Apparently the EU uses CC 4.0 now, so I chose CC BY 4.0.

**Comment by MansMeg** [comment]
Great!

**Pull request merged**
