### PR TITLE
Curation 1890s

### PR DESCRIPTION
**Pull request by BobBorges**
more data

### CODE REVIEW

**Comment by ninpnin** [comment]
Segmentat classificationa accuracy 81.5%. I think we can still merge.

**Comment by MansMeg** [comment]
Yes. We can the improve this later on.

**Comment by ninpnin** [comment]
Apparently a lot of this was due to the OCR merging margins with the text body next to them. We have seen this before, is there an issue for fixing it?

**Comment by MansMeg** [comment]
Im not sure. File an issue describing the problem, maybe with an example.

**Comment by ninpnin** [comment]
#250

**Pull request merged**
