### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by BobBorges**
Update plots in readme.

### CODE REVIEW

**Comment by BobBorges** [comment]
well.. [edit] ~~stats dashboard~~  Notebooks needs a bit of fixin'. Will get on that asap.

**Comment by ninpnin** [comment]
To make sure we run all the tests, this is what we have in the workflow file now:

```bash
name: Perform unit tests
        python -m unittest test.schemas
        python -m unittest test.altocheck
        python -m unittest test.chairs
        python -m unittest test.mp
        python -m unittest test.next_prev
        python -m unittest test.paragraph_has_id
        python -m unittest test.db
```

**Comment by MansMeg** [comment]
Great that you split these Väinö!

**Comment by MansMeg** [comment]
Still failing tests?

**Review by ninpnin — APPROVED** [review]

**Pull request merged**
