### PR TITLE
feat: mapping between swerik_ids and biobook references

### PR DESCRIPTION
**Pull request by BobBorges**
Here's a mapping between swerik IDs and the bio-books.

I found 172 individuals in the mp metadata that didn't make it into the known_mp_catalog, thus not in the mapping. 147 of them have a biobook reference that we know of, but the volume / pages would have to be looked up or fetched from wikidata - is that something we want to handle before merging this file? I need to use it for other stuff, but it can sit in PR for a while.

- unreferenced MPs with a biobook reference 
[unreferenced-mps.csv](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14211492/unreferenced-mps.csv)

- the list of IDs not in the mapping file
[unreferenced-MPs.txt](https://github.com/welfare-state-analytics/riksdagen-corpus/files/14211493/unreferenced-MPs.txt)

### CODE REVIEW

**Comment by fredrik1984** [comment]
Ok, good to know! I leave that decision to @MansMeg or @ninpnin

**Comment by BobBorges** [comment]
@ninpnin Pls take a look /merge

**Comment by MansMeg** [comment]
Should we open up a new issue to fix the last things?

**Comment by ninpnin** [comment]
I think we should add a description in corpus/metadata/README.md . Otherwise looks fine by me.

**Review by ninpnin — APPROVED** [review]

**Pull request merged**
