### PR TITLE
added file over riksdagen (vice) talmän

### PR DESCRIPTION
**Pull request by rbbby**
Added file over riksdagens (vice) talmän. Exact dates is currently incomplete but is being worked on.

### CODE REVIEW

**Comment by ninpnin** [comment]
Couple of things that we need to fix:

- [ ] The party names should be harmonized with the other lists
- [x] Some IDs have spaces in them, we need to replace them with underscores

Some not so crucial things:

- The unicameral era might be better to be indicated with an actual value instead of NaN

And finally, we need

- [x] The algorithm needs to go through talmän in addition to MPs and ministers

**Comment by rbbby** [comment]
> Couple of things that we need to fix:
> 
>     * [ ]  The party names should be harmonized with the other lists
> 
>     * [ ]  Some IDs have spaces in them, we need to replace them with underscores
> 
> 
> Some not so crucial things:
> 
>     * The unicameral era might be better to be indicated with an actual value instead of NaN
> 
> 
> And finally, we need
> 
>     * [ ]  The algorithm needs to go through talmän in addition to MPs and ministers

Fixed ids and unicameral era. 2-3 party abbreviations are unclear and will be added later.

**Comment by ninpnin** [comment]
Is this ready to be merged?

**Comment by rbbby** [comment]
believe it is ready for merge now!

**Comment by ninpnin** [comment]
LGTM

**Pull request merged**
