### PR TITLE
v0.4.5

### PR DESCRIPTION
**Pull request by rbbby**

### CODE REVIEW

**Comment by MansMeg** [comment]
Just a question, it doesnt seem like we have changed any protocols here? We want to update the speaker information in the minutes/protocols as well?

**Comment by rbbby** [comment]
Oops, great that you noticed! I forgot to push the corpus. Rerunning some scripts and fixing it atm.

**Comment by ninpnin** [comment]
That actually makes the PR more legible as you actually get the diffs 😅

**Comment by MansMeg** [comment]
Do you do a release on the webpage as well?

**Comment by rbbby** [comment]
Do you mean like this or something else?
https://github.com/welfare-state-analytics/riksdagen-corpus/releases/tag/v0.4.5

**Comment by MansMeg** [comment]
Yes! Great work!

**Pull request merged**
