### PR TITLE
0.4.3

### PR DESCRIPTION
**Pull request by rbbby**

### CODE REVIEW

**Comment by rbbby** [comment]
I have gone through many of the new unknowns in the new dip of 1974 and all of them were previously incorrectly classified as the wrong people, so LGTM.

**Comment by MansMeg** [comment]
Great! Can you update the README as well?

**Comment by rbbby** [comment]
> Great! Can you update the README as well?

@ninpnin fixed it.

**Comment by MansMeg** [comment]
Yay!

**Pull request merged**
