### PR TITLE
Bert intros

### PR DESCRIPTION
**Pull request by rbbby**
BERT models for 1. intro detection and 2. merging of split intros has now been implemented. It seems to work well but there are bugs for how intros detected in textblocks tagged as "seg" is being handled. First of u-tags etc are not updated and a new speaker may be detected within another persons speech. Second, these "seg"-introductions are ignored in redetect. 

The script used to detect new intros is resegment-bert.py. Intros are joined on the fly during redetect. Both makes use of already made predictions in input/segmentation/intros.csv and input/segmentation/join_intros.csv

We should look over where and how to solve this bug (and solve it) before a release.

Example (there are ~a couple of these in each protocol):
corpus/protocols/1967/prot-1967-höst-ak--46.xml
i-oaWdhCjoVLPKzpaMiFLUc

### CODE REVIEW

**Comment by MansMeg** [comment]
Great! Will you be able to fix the bug?

**Comment by MansMeg** [comment]
Or do you need help?

**Comment by rbbby** [comment]
I would need some help. There is a lot going on in the old code which I am not familiar with.

**Comment by MansMeg** [comment]
Alright, then I guess @ninpnin is best to discuss with.

**Pull request closed without merging**
