### PR TITLE
v0.13.0

### PR DESCRIPTION
**Pull request by ninpnin**

### CODE REVIEW

**Comment by ninpnin** [comment]
@BobBorges can we merge? It's the same commit anyway

**Comment by MansMeg** [comment]
Nah. Let the tests runnso we are sure. We dont want a failing main when we leave for weekend.

**Comment by MansMeg** [comment]
Alright! Lets release!

**Comment by BobBorges** [comment]
I can't seem to make a review because the diffs won't load, but everything has been checked in individual PRs, tests pass, and there are no merge conflicts. I think it's time.

**Comment by MansMeg** [comment]
Boom! Done!

**Pull request merged**
