### PR TITLE
v0.3.1

### PR DESCRIPTION
**Pull request by ninpnin**
- Add metadata in teiHeaders

### CODE REVIEW

**Comment by ninpnin** [comment]
Screenshot 2021-12-27 at 16 39 07

- Added licence information
- Changed the correction to 'some changes were made' from 'no changes were made'
- Changed the edition to 0.3
- Changed the authority (copyright holder AFAIK) to the Westac project

Is this enough?

**Comment by MansMeg** [comment]
Looks good to me!

**Comment by MansMeg** [comment]
Github action currently fails @ninpnin

**Comment by ninpnin** [comment]
@MansMeg I think that is some logging that we don't need anymore. The tests themselves pass fine.

**Comment by MansMeg** [comment]
Ok. I file it as a bug. We should fix so that github actions work as expected and I don't get messages about failed tests. =)

**Pull request merged**
