### PR TITLE
Remove R package

### PR DESCRIPTION
**Pull request by MansMeg**
Hi!

I have moved the R package to a separate repository and added some information in the README.

I also moved the SWERIK presentation to supplementary materials.

### CODE REVIEW

**Comment by MansMeg** [comment]
It seems like the unit test checks that the presentation ppt is part of the root?

**Comment by BobBorges** [comment]
> It seems like the unit test checks that the presentation ppt is part of the root?

I think it fails because the parentheses are not escaped in `(eng)`
image

**Comment by BobBorges** [comment]
I pushed  commit that _might_ fix the problem, but probably we should revert the workflow file after, since the change makes it less efficient (calls `test/unchanged.py` once on each file instead of once on all files).

This is a good lesson on not putting spaces and other spooky stuff in file paths.

**Comment by BobBorges** [comment]
Nah, it still fails. @MansMeg I don't know how proper it would be in this case, but we could not run this unit test this time around, or if the unit test failing doesn't block the merge, just merge anyway. I either of these options would cause an issue with this file until the delete is merged into main.

@ninpnin do you have any idea how to correctly handle this? Changing the name will cause the unit test to fail in the same way.

**Comment by ninpnin** [comment]
I think the "don't ever make changes to these files" requirement is outdated.

I.e. we could remove that test.

**Comment by BobBorges** [comment]
The `unchanged.py` unit test didn't actually check anything, only that the directory (not it's content) `input/curation/` isn't listed in the changed/deleted files. Removed from the workflow & should fix the problem here.

**Review by BobBorges — APPROVED** [review]

**Pull request merged**
