### PR TITLE
v0.12.0

### PR DESCRIPTION
**Pull request by ninpnin**

### CODE REVIEW

**Comment by MansMeg** [comment]
Seem to be an error in the dev branch now.

**Comment by ninpnin** [comment]
It's the same thing, no zip has been generated for the latest release so the notebook crashes.

**Comment by MansMeg** [comment]
Ok. So we only wait for a go-ahead from Bob?

**Comment by MansMeg** [comment]
But wait. Will this test crash in main as well? Then we need to fix the test. We should not have failing tests in main.

**Review by BobBorges — APPROVED** [review]

**Pull request merged**
