### PR TITLE
v0.11.0

### PR DESCRIPTION
**Pull request by ninpnin**

### CODE REVIEW

**Comment by MansMeg** [comment]
Should we release it or try to merge the last prs to dev first. Rm r package make sense since its small.

**Comment by ninpnin** [comment]
I don't think it makes sense to delay a release until we sort out a test technicality, if making releases is cheap

**Comment by MansMeg** [comment]
I agree. We want rapid releases.

**Review by MansMeg — APPROVED** [review]
Its hard to review this full release since there are too many files. But since the reviews going into dev has been reviewed Im happy to approve.

**Comment by BobBorges** [comment]
Test pass and everything has been reviewed. 
image
maybe merge #356 and #431 into dev first (if the test pass on the last pushes).

**Comment by MansMeg** [comment]
Alright! Maybe just release it and do another quick release with the other PRs?

**Comment by BobBorges** [comment]
Dunno what happened with #356, but it's fixed.

**Pull request merged**
