### PR TITLE
Years1910to1920

### PR DESCRIPTION
**Pull request by BobBorges**
There's data from 1910 to/incl 1919. I also added/edited some files in `scripts/` and `pyriksdagen/`.

### CODE REVIEW

**Comment by MansMeg** [comment]
Failing test suite?

**Review by ninpnin — APPROVED** [review]
LGTM

**Comment by BobBorges** [comment]
wreszcie -- at last

**Comment by MansMeg** [comment]
Who will get the honor to merge? I suggest this is 0.6.0 since adding new data is essentially a new feature?

**Pull request merged**
