### PR TITLE
Deprecate Repo

### PR DESCRIPTION
**Pull request by BobBorges**
- **docs: generate a new accuracy plot**
  

- **docs: update README**
  

- **chore: build module**
  

- **chore: update version plot**
  

- **fix: repl. 'wiki_id' w/ 'swerik_id'**
  

- **fix: repl. wiki_id w/ swerik_id**
  

- **test: split tests into multiple workflows**
  

- **chore: update corpus version**
  

- **chore:update version nr**
  

- **fix: test that takes ages**
  

- **docs: generate a new accuracy plot**
  

- **docs: update README**
  

- **chore: build module**
  

- **add swerik id**
  

- **2024-01-18_reviewing_chairs**
  

- **2024-01-19_reviewing_chairs**
  

- **feat: add unittest based on manually curated data**
  

- **2024-01-22_reviewing_chairs**
  

- **fix: actually run the test**
  

- **fix: renamed pyriksdagen function**
  

- **2022_01_23_1/2_reviewing_chairs**
  

- **2022-01-23_reviewing_chairs_2/2**
  

- **2023_01_24_reviewing_chairs**
  

- **feat: pass args to unittests when running locally**
  

- **fix: handle dates better (sorry for this hot mess)**
  

- **2023-01-25_reviewing_chairs**
  

- **2024-01-26_reviewing_chairs**
  

- **2024_01_29_reviewing_chairs**
  

- **feat: impute MP dates based on riksdagår start-end**
  

- **fix: 1923 did not start in 1905**
  

- **refactor: work with new date handling implementation**
  

- **fix: most recent version line on top of z-index**
  

- **chore: update after new date handling**
  

- **refactor: rewrite pipeline from scratch**
  

- **refactor: use external library for ALTO XML**
  

- **refactor: add XML_NS as a shared variable for the package**
  

- **fix: correct amount of padding when printing XML**
  

- **refactor: rewrite pipeline from scratch**
  

- **fix: digital originals pipeline**
  

- **fix: missing dependency**
  

- **refactor: remove unnecessary code**
  

- **fix: make digital originals first ID unique**
  

- **fix: archive login bug**
  

- **feat: check what protocols exist and run pipeline with the same script**
  

- **fix: remove debugging 'break' statement**
  

- **fix: remove unnecessary imports**
  

- **refactor: split ALTO processing into three functions for generalizability**
  

- **fix: add docstring and wrong var bug**
  

- **feat:pipe local alto files**
  

- **pull from other working branch**
  

- **fix: date inclusivity**
  

- **chore: reformat csv (comma, no extra cols)**
  

- **fix: paragraph ID seed**
  

- **fix: some errors**
  

- **fix: better date handling**
  

- **feat: mapping between swerik_ids and biobook references**
  

- **fix: rm edition statement**
  

- **fix: sort local input filenames**
  

- **fix: remove default version number**
  

- **fix: errors failing the tests**
  

- **fix: errors failing the tests**
  

- **fix: change stupid filename**
  

- **chore: pull from wd**
  

- **docs: describe references_map file**
  

- **reviewing_chairs_2024-02-12**
  

- **reviewing_chairs_2024-02-14**
  

- **reviewing_chairs_2024-02-19**
  

- **feat: post-1994 iorter, and refactor: start rearranging corpus as planned**
  

- **refactor: relocate db unittest data**
  

- **refactor: db test infiles in new location, write local output according to config / pytestconfig**
  

- **chore: query metadata after adding moder orter**
  

- **chore: add readme**
  

- **fix: path stuff**
  

- **reviewing_chairs_2024-02-21**
  

- **fix: sort chair_mp.csv**
  

- **fix: sort chair_mp.csv properly**
  

- **fix: sort chair_mp.csv properly**
  

- **fix: remove duplicates**
  

- **feat: new test**
  

- **feat: get outpath for all test results**
  

- **feat: run empty speeches test on push**
  

- **style: cleaning up formatting**
  

- **fix: filename**
  

- **refactor: input file paths as argparse args**
  

- **docs: generate a new accuracy plot**
  

- **docs: update README**
  

- **chore: build module**
  

- **chore...want to switch branch:**
  

- **feat: add depreciation warning**

### CODE REVIEW

**Comment by ninpnin** [comment]
The technical term is [_deprecated_](https://en.wikipedia.org/wiki/Deprecation) 😅

**Comment by BobBorges** [comment]
Interestingly enough, the origin of "deprecate" is a misspelling of "depreciate" in a technical article... if you believe in urban legends, that is.

**Comment by ninpnin** [comment]
Yup. The only reason I'm mentioning this is since this is probably the second-most public facing thing we put out.

**Review by ninpnin — APPROVED** [review]
🔥🔥🔥

**Comment by ninpnin** [comment]
Along with this, we want to push the Archive Repo button in the repo settings.

**Pull request merged**
